micronaut:
  application:
    name: scorekeep
---
micronaut:
  server:
    cors:
      enabled: true
      configurations:
        all:
          allowed-methods: "*"
          allowed-headers: "*"
          allowed-origins: "http://localhost:8080"
---
micronaut:
  router:
    static-resources:
      frontend:
        paths: 'classpath:public'